// Codegen: bundle the historical-figure Markdown fixtures into a committed TS
// module so consumers that only see `dist/` (e.g. the server importing this as
// an npm package) get the content. `tsc` does not copy `.md` files, so the
// canonical text lives in `.md` files under
// `src/fixtures/historical-figures/<figureCurationId>/` and is baked into
// `content.generated.ts` here.
//
// Each figure folder holds exactly three Markdown files:
//   - `about.md`             — about the figure (keyed by figureCurationId)
//   - `<docId>.md`           — the source-document text (keyed by docId)
//   - `<docId>-about.md`     — about that document (keyed by docId)
//
// This script is run by `pnpm run gen:fixtures`, which also runs at the start
// of `build`, so `dist/` always reflects the current `.md` files.

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ABOUT_BASENAME = "about"
const ABOUT_SUFFIX = "-about"
const MD_EXT = ".md"

const here = dirname(fileURLToPath(import.meta.url))
const figuresDir = join(here, "..", "src", "fixtures", "historical-figures")
const outputPath = join(figuresDir, "content.generated.ts")

const figureAbout: [string, string][] = []
const documentMarkdown: [string, string][] = []
const documentAbout: [string, string][] = []

const figureDirs = readdirSync(figuresDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

for (const figureCurationId of figureDirs) {
    const dirPath = join(figuresDir, figureCurationId)
    const mdFiles = readdirSync(dirPath).filter((name) => name.endsWith(MD_EXT))
    for (const fileName of mdFiles) {
        const base = fileName.slice(0, fileName.length - MD_EXT.length)
        const content = readFileSync(join(dirPath, fileName), "utf8")
        if (base === ABOUT_BASENAME) {
            figureAbout.push([figureCurationId, content])
        } else if (base.endsWith(ABOUT_SUFFIX)) {
            const docId = base.slice(0, base.length - ABOUT_SUFFIX.length)
            documentAbout.push([docId, content])
        } else {
            documentMarkdown.push([base, content])
        }
    }
}

function renderMap(name: string, entries: [string, string][]): string {
    const lines = [...entries]
        .sort((a, b) => a[0].localeCompare(b[0]))
        .map(
            ([key, value]) =>
                `    ${JSON.stringify(key)}: ${JSON.stringify(value)},`
        )
    return `export const ${name}: Record<string, string> = {\n${lines.join(
        "\n"
    )}\n}\n`
}

const header =
    "// AUTO-GENERATED by scripts/gen-fixtures-content.ts — do not edit by hand.\n" +
    "// Source of truth: the .md files under\n" +
    "// src/fixtures/historical-figures/<figureCurationId>/.\n" +
    "// Regenerate with `pnpm run gen:fixtures` (runs at the start of `build`).\n\n"

const body = [
    renderMap("figureAboutByCurationId", figureAbout),
    renderMap("documentMarkdownByCurationId", documentMarkdown),
    renderMap("documentAboutByCurationId", documentAbout),
].join("\n")

writeFileSync(outputPath, header + body)
console.log(`gen:fixtures — wrote ${outputPath} (${figureDirs.length} figures)`)
